version: "3.9"

services:
  app:
    build:
      context: .
    container_name: django
    ports:
    #local port to docker port
      - "8000:8000"
    volumes:
    #map local app dir to docker app dir
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8000
    #navigate to http://127.0.0.1:8000/ in your browser
    environment:
      - DB_HOST=pgdb
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: postgresql
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  dev-db-data:


